const SITE='https://sites.google.com/deped.gov.ph/hinigaranelementaryschool-b/home';
const KEY='eHESB_CONTENT_V1', LOGIN='eHESB_ADMIN_SESSION';
const defaults={announcements:[{title:'Welcome to PROJECT eHES-B',body:'This is the mobile dashboard for Hinigaran Elementary School-B.',date:'School Update'}],
events:[{title:'School Activities',body:'Add upcoming programs, celebrations and meetings here.',date:'Upcoming'}],
resources:[{title:'Reading',body:'Reading materials and intervention resources.',url:''},{title:'Mathematics',body:'Worksheets and practice activities.',url:''},{title:'Science',body:'Learning activities and resources.',url:''},{title:'ICT',body:'Digital literacy resources.',url:''}],
projects:[{title:'PROJECT FLAMES',body:'School-based learner development initiative.'},{title:'PROJECT KANTAHA',body:'School program supporting participation and engagement.'},{title:'PROJECT REPORT',body:'Reading Enhancement Promotes Orderly Responsive Teaching.'},{title:'WASH in Schools',body:'Health, sanitation and hygiene initiatives.'},{title:'PROJECT eHES-B',body:'QR-enabled school digital gateway.'}],
forms:[{title:'Digital Forms Center',body:'Official school forms, requests and downloadable documents.',url:''}],
gallery:[]};
function data(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch(e){return structuredClone(defaults)}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));render()}
function openSite(){window.open(SITE,'_blank')}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.getElementById('nav').classList.remove('show');if(id==='admin')showLogin();scrollTo({top:0,behavior:'smooth'})}
document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('show');
document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.page)));
function openAdmin(){go('admin')}
function login(){if(document.getElementById('adminPass').value==='HESBadmin2026'){sessionStorage.setItem(LOGIN,'1');showDashboard()}else alert('Incorrect prototype password.')}
function logout(){sessionStorage.removeItem(LOGIN);showLogin()}
function showLogin(){if(sessionStorage.getItem(LOGIN)==='1')showDashboard();else{document.getElementById('loginBox').style.display='block';document.getElementById('dashboard').style.display='none'}}
function showDashboard(){document.getElementById('loginBox').style.display='none';document.getElementById('dashboard').style.display='block';adminTab('announcements')}
function adminTab(type){const d=data(), labels={announcements:'Announcements',events:'Events',resources:'Learning Resources',projects:'Programs & Projects',forms:'Forms',gallery:'Gallery'};let h=`<h3>Manage ${labels[type]}</h3><button onclick="addItem('${type}')">＋ Add New</button><div>`;(d[type]||[]).forEach((x,i)=>{h+=`<div class="item"><b>${esc(x.title||x.name||'Untitled')}</b><p>${esc(x.body||'')}</p><button onclick="editItem('${type}',${i})">Edit</button><button class="danger" onclick="deleteItem('${type}',${i})">Delete</button></div>`});h+='</div>';document.getElementById('editor').innerHTML=h}
function addItem(type){const title=prompt('Title / name:');if(!title)return;const body=prompt('Description / announcement:')||'';const d=data();if(!d[type])d[type]=[];d[type].push({title,body,date:'',url:''});save(d);adminTab(type)}
function editItem(type,i){const d=data(),x=d[type][i];const title=prompt('Edit title:',x.title||'');if(title===null)return;const body=prompt('Edit description:',x.body||'');if(body===null)return;x.title=title;x.body=body;save(d);adminTab(type)}
function deleteItem(type,i){if(!confirm('Delete this item?'))return;const d=data();d[type].splice(i,1);save(d);adminTab(type)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){const d=data();document.getElementById('newsList').innerHTML=d.announcements.map(x=>`<article><label>${esc(x.date||'ANNOUNCEMENT')}</label><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')||'<article>No announcements yet.</article>';document.getElementById('eventList').innerHTML=d.events.map(x=>`<article><label>${esc(x.date||'EVENT')}</label><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('');document.getElementById('learnList').innerHTML=d.resources.map(x=>`<article>📚<h3>${esc(x.title)}</h3><p>${esc(x.body)}</p>${x.url?`<a target="_blank" href="${esc(x.url)}">Open resource →</a>`:''}</article>`).join('');document.getElementById('projectList').innerHTML=d.projects.map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('');document.getElementById('formList').innerHTML=d.forms.map(x=>`<article><h3>📄 ${esc(x.title)}</h3><p>${esc(x.body)}</p>${x.url?`<a target="_blank" href="${esc(x.url)}">Open form →</a>`:''}</article>`).join('');document.getElementById('knightList').innerHTML='<article><h3>Achievement Center</h3><p>Sports results and HES-B Knights updates can be added in the production content manager.</p></article>';document.getElementById('galleryList').innerHTML=d.gallery.length?d.gallery.map(x=>`<div>${esc(x.title)}</div>`).join(''):'<div>HES-B<br><small>Official photos can be added in the production version.</small></div>'}
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js', {scope: './'}).catch(()=>{});